/**
 * Seed Data - Achievements
 * Based on PRD gamification system
 */

import { Prisma } from '@prisma/client';

export const achievements: Prisma.AchievementCreateInput[] = [
  // Earning achievements
  {
    code: 'FIRST_BLOOD',
    name: 'First Blood',
    description: 'Earn your first 100 CAP',
    category: 'milestone',
    requirementType: 'cap_total',
    requirementValue: 100,
    rewardCap: 50,
    rewardBadge: 'first_blood',
    iconUrl: '/achievements/first-blood.png',
    sortOrder: 1,
  },
  {
    code: 'CAP_COLLECTOR_1000',
    name: 'CAP Collector',
    description: 'Earn 1,000 total CAP',
    category: 'milestone',
    requirementType: 'cap_total',
    requirementValue: 1000,
    rewardCap: 100,
    rewardBadge: 'collector_1000',
    iconUrl: '/achievements/collector.png',
    sortOrder: 2,
  },
  {
    code: 'CAP_COLLECTOR_10000',
    name: 'CAP Enthusiast',
    description: 'Earn 10,000 total CAP',
    category: 'milestone',
    requirementType: 'cap_total',
    requirementValue: 10000,
    rewardCap: 500,
    rewardBadge: 'enthusiast',
    iconUrl: '/achievements/enthusiast.png',
    sortOrder: 3,
  },
  {
    code: 'CAP_COLLECTOR_100000',
    name: 'CAP Master',
    description: 'Earn 100,000 total CAP',
    category: 'milestone',
    requirementType: 'cap_total',
    requirementValue: 100000,
    rewardCap: 2000,
    rewardBadge: 'master',
    iconUrl: '/achievements/master.png',
    sortOrder: 4,
  },

  // Engagement achievements
  {
    code: 'SOCIAL_BUTTERFLY',
    name: 'Social Butterfly',
    description: 'Share 50 ads',
    category: 'social',
    requirementType: 'shares',
    requirementValue: 50,
    rewardCap: 200,
    rewardBadge: 'social_butterfly',
    iconUrl: '/achievements/social.png',
    sortOrder: 5,
  },
  {
    code: 'CRITIC',
    name: 'Critic',
    description: 'Post 100 comments',
    category: 'engagement',
    requirementType: 'comments',
    requirementValue: 100,
    rewardCap: 300,
    rewardBadge: 'critic',
    iconUrl: '/achievements/critic.png',
    sortOrder: 6,
  },
  {
    code: 'TRENDSETTER',
    name: 'Trendsetter',
    description: 'Get 50 accepted suggestions',
    category: 'engagement',
    requirementType: 'suggestions_accepted',
    requirementValue: 50,
    rewardCap: 500,
    rewardBadge: 'trendsetter',
    iconUrl: '/achievements/trendsetter.png',
    sortOrder: 7,
  },
  {
    code: 'SUGGESTION_MASTER',
    name: 'Suggestion Master',
    description: 'Submit 100 suggestions',
    category: 'engagement',
    requirementType: 'suggestions',
    requirementValue: 100,
    rewardCap: 400,
    rewardBadge: 'suggestion_master',
    iconUrl: '/achievements/suggestion.png',
    sortOrder: 8,
  },
  {
    code: 'LIKE_MACHINE',
    name: 'Like Machine',
    description: 'Give 500 likes',
    category: 'engagement',
    requirementType: 'likes',
    requirementValue: 500,
    rewardCap: 250,
    rewardBadge: 'like_machine',
    iconUrl: '/achievements/like.png',
    sortOrder: 9,
  },

  // Social achievements
  {
    code: 'NETWORKER',
    name: 'Networker',
    description: 'Refer 10 friends',
    category: 'social',
    requirementType: 'referrals',
    requirementValue: 10,
    rewardCap: 2000,
    rewardBadge: 'networker',
    iconUrl: '/achievements/networker.png',
    sortOrder: 10,
  },
  {
    code: 'INFLUENCER',
    name: 'Influencer',
    description: 'Gain 1,000 followers',
    category: 'social',
    requirementType: 'followers',
    requirementValue: 1000,
    rewardCap: 1000,
    rewardBadge: 'influencer',
    iconUrl: '/achievements/influencer.png',
    sortOrder: 11,
  },

  // Streak achievements
  {
    code: 'STREAK_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    category: 'milestone',
    requirementType: 'streak_days',
    requirementValue: 7,
    rewardCap: 100,
    rewardBadge: 'week_warrior',
    iconUrl: '/achievements/week.png',
    sortOrder: 12,
  },
  {
    code: 'STREAK_30',
    name: 'Month Master',
    description: 'Maintain a 30-day streak',
    category: 'milestone',
    requirementType: 'streak_days',
    requirementValue: 30,
    rewardCap: 500,
    rewardBadge: 'month_master',
    iconUrl: '/achievements/month.png',
    sortOrder: 13,
  },
  {
    code: 'STREAK_100',
    name: 'Streak Legend',
    description: 'Maintain a 100-day streak',
    category: 'milestone',
    requirementType: 'streak_days',
    requirementValue: 100,
    rewardCap: 2000,
    rewardBadge: 'streak_legend',
    iconUrl: '/achievements/streak.png',
    sortOrder: 14,
  },

  // Room achievements
  {
    code: 'ROOM_EXPLORER',
    name: 'Room Explorer',
    description: 'Join 50 different rooms',
    category: 'engagement',
    requirementType: 'rooms_joined',
    requirementValue: 50,
    rewardCap: 300,
    rewardBadge: 'room_explorer',
    iconUrl: '/achievements/room.png',
    sortOrder: 15,
  },
  {
    code: 'CHAT_ACTIVE',
    name: 'Chat Active',
    description: 'Send 500 messages in rooms',
    category: 'engagement',
    requirementType: 'messages',
    requirementValue: 500,
    rewardCap: 400,
    rewardBadge: 'chat_active',
    iconUrl: '/achievements/chat.png',
    sortOrder: 16,
  },

  // Purchase achievements
  {
    code: 'FIRST_PURCHASE',
    name: 'First Purchase',
    description: 'Make your first purchase in the marketplace',
    category: 'milestone',
    requirementType: 'purchases',
    requirementValue: 1,
    rewardCap: 100,
    rewardBadge: 'first_purchase',
    iconUrl: '/achievements/first-purchase.png',
    sortOrder: 17,
  },
  {
    code: 'SHOPAHOLIC',
    name: 'Shopaholic',
    description: 'Make 20 purchases',
    category: 'shopping',
    requirementType: 'purchases',
    requirementValue: 20,
    rewardCap: 500,
    rewardBadge: 'shopaholic',
    iconUrl: '/achievements/shop.png',
    sortOrder: 18,
  },

  // Review achievements
  {
    code: 'REVIEWER',
    name: 'Reviewer',
    description: 'Write 10 product reviews',
    category: 'engagement',
    requirementType: 'reviews',
    requirementValue: 10,
    rewardCap: 200,
    rewardBadge: 'reviewer',
    iconUrl: '/achievements/review.png',
    sortOrder: 19,
  },
  {
    code: 'HELPFUL_REVIEWER',
    name: 'Helpful Reviewer',
    description: 'Get 50 helpful votes on your reviews',
    category: 'engagement',
    requirementType: 'helpful_votes',
    requirementValue: 50,
    rewardCap: 300,
    rewardBadge: 'helpful_reviewer',
    iconUrl: '/achievements/helpful.png',
    sortOrder: 20,
  },

  // Special achievements
  {
    code: 'EARLY_ADOPTER',
    name: 'Early Adopter',
    description: 'Join VIRAZ in the first month',
    category: 'special',
    requirementType: 'registration_date',
    requirementValue: 0,
    rewardCap: 500,
    rewardBadge: 'early_adopter',
    iconUrl: '/achievements/early.png',
    sortOrder: 21,
  },
  {
    code: 'BUG_HUNTER',
    name: 'Bug Hunter',
    description: 'Report 10 verified bugs',
    category: 'special',
    requirementType: 'bug_reports',
    requirementValue: 10,
    rewardCap: 1000,
    rewardBadge: 'bug_hunter',
    iconUrl: '/achievements/bug.png',
    sortOrder: 22,
  },
];